# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo-prestamype
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./restapi-nodejs-mongodb/data:/data/db
    networks:
      - mongo-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express-prestamype
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
